---
- hosts: es
  remote_user: root
  tasks:
    - name: example copying file with owner and permissions
      copy:
        src: hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
    - shell: reboot
